version: '3'

networks:
  flashcard-app-network:
    external: true
    driver: bridge

services:
  be:
    image: zzzz465/flashcard-be:latest
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - NODE_ENV=production
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] Node.js version: 14, 12, 10
        VARIANT: 14
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000

    depends_on:
      - db
    # ports:
      # - "4000:3001" # expose server port 3001 to localhost:4000
      
    # Overrides default command so things don't shut down after the process ends.
    command: npm run start:prod

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    # network_mode: bridge
    networks:
      - flashcard-app-network

    # Uncomment the next line to use a non-root user for all processes.
    # user: node

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgresDB:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: flashcard

    # network_mode: bridge
    networks:
      - flashcard-app-network

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

volumes:
  postgresDB:
